### ISSUE TITLE
Publish to Homebrew

### ISSUE THREAD

**Issue by davemackintosh** [tonsky/AnyBar#10]
I would absolutely love to create some plugins for my automated tasks so I don't have to tab to them, any chance you could publish this to Homebrew? https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook

**Comment by tonsky** [comment]
I don’t know, does it even makes sense? AnyBar is a client application, you can just download it. Right? I thought homebrew was for console, compile-from-sources, run in terminal stuff?

**Comment by davemackintosh** [comment]
Apart from the menu bar itself does it have a GUI? I'd say it was worth it for the folks who only have homebrew installed. Would improve/automate update rollout and people who want to use it as a dependency of other another project as well.

**Comment by frdmn** [comment]
For GUI applications there is [homebrew-cask](https://github.com/caskroom/homebrew-cask) which is like a addon for `brew`. Once installed it adds a sub command (`brew cask`) that can be used to update, install and uninstall tons of Mac apps: https://github.com/caskroom/homebrew-cask/tree/master/Casks

**Comment by justincampbell** [comment]
Would love to see this in brew cask

**Comment by skibz** [comment]
`brew cask` - do it.

**Comment by tonsky** [comment]
Apparently it’s already added by @wmorin https://github.com/caskroom/homebrew-cask/pull/9911
Thanks Willy!

**Comment by wmorin** [comment]
You're welcome, and thank you @tonsky for the fabulous AnyBar!

**Comment by davemackintosh** [comment]
Thanks @wmorin!
