### ISSUE TITLE
Using in a shell script

### ISSUE THREAD

**Issue by lanej0** [tonsky/AnyBar#17]
When I try to use anybar from a shell script, I can't seem to get it to change the icon to anything but "question".  I'm sure that it's something I'm doing wrong.  It is actually changing the icon, but it's like the colour isn't getting sent through properly?  I've tried using single quotes, escaping the quotes -- what am I doing wrong?

``` sh
#!/bin/sh
echo -n "black" | nc -4u -w0 localhost 1738
```

**Comment by tonsky** [comment]
Use #!/bin/bash
Looks like sh does not know -n option for echo:

From man echo:

> Most notably, the builtin echo in sh(1) does not accept the -n option.

**Comment by lanej0** [comment]
Thank you.  That did the trick!

**Comment by pruppert** [comment]
Same problem here. Won't run from within a script, even after trying this:

```
#!/bin/bash
echo -n "black" | nc -4u -w0 localhost 1738
```
Any ideas?
