### ISSUE TITLE
Allow the menubar icon to be moved with the command-click shortcut

### ISSUE THREAD

**Issue by VFS** [tonsky/AnyBar#21]
Some icons can be rearranged by command+click/drag. Please implement this feature so I can easily keep my menubar organised without having to buy bartender.

**Comment by tonsky** [comment]
Do you know how this can be implemented? I see that only system icons are draggable. Is it even possible for userspace apps?

**Comment by VFS** [comment]
It can be implemented because the iStat app allow the user to do that, but I couldn't find any reference on how to accomplish that (I'm new to OSX developmen).

**Comment by perfaram** [comment]
It's a private API that only Apple uses... 
Actually, apps icons and stock Apple icons in the menu bar are managed differently, in two different ways:
1. Apple icons are managed by the `SystemUIServer`, and unless you're able to hack your way into it, you can't use it (iStat guys did it, so it's possible).
2. The `classic` app icons, managed by the app they belong to.

**Comment by tonsky** [comment]
Ok, I’ll close it for now then. I’m thinking to add multiple icons/ports in a single app, this should solve a problem of organizing AnyBar icons at least.

**Comment by moshed** [comment]
sierra allows this by the way
