### ISSUE TITLE
Set tooltip

### ISSUE THREAD

**Issue by sindresorhus** [tonsky/AnyBar#23]
This might be out of scope of this app, but it would be useful to be able to set a tooltip for the menubar app, from a client. This is especially useful when you have multiple instances of AnyBar so you can distinguish them.

**Comment by jessereynolds** [comment]
this was my first thought, too.

**Comment by steverobbins** [comment]
:+1:

**Comment by tgray** [comment]
https://github.com/ttscoff/AnyBar

**Comment by tonsky** [comment]
Possible in 0.2.0 via ANYBAR_TITLE env var
