### ISSUE TITLE
What Font is used in the screenshot

### ISSUE THREAD

**Issue by ZucchiniZe** [tonsky/AnyBar#25]
I was wondering what font that @tonsky used in the screenshot.

**Comment by codyphobe** [comment]
Looks like [San Francisco](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/WatchHumanInterfaceGuidelines/ColorandTypography.html).

**Comment by tonsky** [comment]
That’s right https://github.com/supermarin/YosemiteSanFranciscoFont
