### ISSUE TITLE
When downloaded it did not work

### ISSUE THREAD

**Issue by voronoipotato** [tonsky/AnyBar#27]
When I downloaded anybar, and tried to set the color, the icon turned clear and would not respond to any color setting. When I used cask to install it worked just fine. 
![screen shot 2015-04-11 at 10 08 07 am](https://cloud.githubusercontent.com/assets/315863/7101683/dfcfd7ca-e032-11e4-9382-d1baf0cba044.png)

**Comment by tonsky** [comment]
What exact command or tool are you using to set color?

**Comment by voronoipotato** [comment]
`echo -n "black" | nc -4u -w0 localhost 1738`

**Comment by tonsky** [comment]
Strange. Cask version and version from GitHub releases page should be
identical. Don’t know how I can help here

**Comment by voronoipotato** [comment]
Seeems to be working now, perhaps I clicked too hard.
