### ISSUE TITLE
Usage in Swift?

### ISSUE THREAD

**Issue by skonesam** [tonsky/AnyBar#28]
This is only an issue with my rudimentary Swift skills – sorry if it's inappropriate to post here.

That said… any suggestions for how to change the icon in Swift? I've explored NSTask with both echo and via an AppleScript. Establishing a connection using BSD sockets seems like massive overkill (and I haven't been successful in any event.)

**Comment by skonesam** [comment]
Decided it was inappropriate to post here. But… in case anyone is looking and wants to help, here's what I can't get to actually _execute_:

```
let command = "/bin/echo"
let args = ["-n \"black\" | nc -4u -w0 localhost 1738"]
let task = NSTask()

task.launchPath = command
task.arguments = args
task.launch()
```

The command is displayed in the console (both in OS X executable and in playgrounds), but, of course, the color never changes. The command works as it should in terminal.

**Comment by tonsky** [comment]
Sure. Might this help? http://stackoverflow.com/questions/25876189/swift-udp-connection
I see sockets are not easy in Swift, maybe AppleScript access is simpler?

**Comment by skonesam** [comment]
I saw that SO post and wasn't able to make it work. Tried playing around with AppleScript with no luck. Just got it to work via a shell script. Posted below if anyone else is curious on the (likely very, very wrong) way I worked around my own limitations…

```
let command = "/full/path/goes/here/anybar.sh"
let args = ["red"]
let task = NSTask()
task.launchPath = command
task.arguments = args
task.launch()
```

shell script, below, taken directly from readme:

```
#!/bin/bash
echo -n $1 | nc -4u -w0 localhost ${2:-1738};
```

**Comment by codyphobe** [comment]
Your first attempt is very close; the command should be `/bin/bash` (or whatever the preferred shell is) instead of `/bin/echo`:

``` swift
let command = "/bin/bash"
let args = ["-c", "echo -n \"black\" | nc -4u -w0 localhost 1738"]
let task = NSTask()

task.launchPath = command
task.arguments = args
task.launch()
```

> **bash -c _string_**
> If the -c option is present, then commands are read from string. If there are arguments after the string, they are assigned to the positional parameters, starting with $0.

**Comment by skonesam** [comment]
Thanks, cs475x! That works perfectly, and is one less external dependency for me to track. I really appreciate it!
