### ISSUE TITLE
Provide instructions on how to launch

### ISSUE THREAD

**Issue by machawk1** [tonsky/AnyBar#29]
Those unfamiliar with Homebrew-cask will likely enter the commands you provide and expect a result. Per the README, I typed `brew cask install anybar` then proceeded to the Usage section, entering `echo -n "black" | nc -4u -w0 localhost 1738`. No icon appeared in my menubar. I checked my Applications directory as linked in the left pane of Finder windows and there is nothing named `Anybar`. A casual user may give up.

Reading the directions provided by Homebrew-cask, I found that the .app was installed in /Users/myusername/Applications/. This can also be found via Spotlight (with the default configuration in OS X 10.10.2) yet the README does not provide any direction on how to launch the app before the Usage instructions can be utilized.

**Comment by tonsky** [comment]
Patch?
