### ISSUE TITLE
Get AnyBar status as open/closed?

### ISSUE THREAD

**Issue by KyleKing** [tonsky/AnyBar#54]
Thanks for making this. I'm using AnyBar to show the status of some of my [Hammerspoon functions](https://github.com/Hammerspoon/hammerspoon) [Lua for mac automation], but I'm having trouble identifying when AnyBar is open or closed. I end up launching duplicate processes or not having a process open. How does everyone else deal with those issues?

But in trying to write my question I think I found a couple of ways to solve this:

``` sh
# A port known to be open returns a line of text
$ sudo nmap -sU -p 1740 $(ipconfig getifaddr en0) | grep open
1740/udp *open*|filtered encore

# While a closed port returns no text
$ sudo nmap -sU -p 9999 $(ipconfig getifaddr en0) | grep open
```

But this method can be prone to [false positives](https://scottlinux.com/2012/06/13/nmap-udp-port-scan-example/). Alternatively, I launch a set number of AnyBar icons, so I can make sure they are open by counting the number of lines returned from the process list ([the [ ] idea was from stackoverflow](http://stackoverflow.com/a/3510850)):

``` sh
$ ps aux | grep -i '[a]nybar'
kyleking         9728   0.0  0.1  2579936  13844   ??  S    10:54AM   0:00.15 /opt/homebrew-cask/Caskroom/anybar/0.1.3/AnyBar.app/Contents/MacOS/AnyBar
kyleking         9726   0.0  0.1  2579936  14020   ??  S    10:54AM   0:00.16 /opt/homebrew-cask/Caskroom/anybar/0.1.3/AnyBar.app/Contents/MacOS/AnyBar
kyleking         9567   0.0  0.1  2579936  14220   ??  S    10:51AM   0:00.33 /opt/homebrew-cask/Caskroom/anybar/0.1.3/AnyBar.app/Contents/MacOS/AnyBar
```

Then to quit the app from a shell prompt, I'm just using:

``` sh
sudo kill $(ps aux | grep -i '[a]nybar' | awk '{print $2}')
```

 Is there a way to build something like this in Applescript or built-in to AnyBar?

**Comment by tonsky** [comment]
I think this is a problem that cannot be addressed by Anybar internally, because, well, it might be not running at all when you need to test it. Hence, this should be solved by external tools. `ps` approach seems ok to me. Do you have any particular issues with it?

**Comment by KyleKing** [comment]
Thanks @tonsky. The `ps` method works much better than expected and I really only wondered if there was a better way

**Comment by Dima-369** [comment]
I found that using `lsof -Pn -i4` is really simple to parse because it lists the application along with its  ports. It outputs:

```
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
AnyBar    44361 Gira    3u  IPv4 0x6ac97d677e737941      0t0  UDP *:1738
AnyBar    44462 Gira    3u  IPv4 0x6ac97d677e7355e9      0t0  UDP *:1739
```

Maybe it's useful for someone :)
