### ISSUE TITLE
Black dot is white when macOS is running in dark mode

### ISSUE THREAD

**Issue by hboon** [tonsky/AnyBar#55]
I'm seeing this in 10.12 beta, but I'm _guessing_ that this might be happening in 10.11 too:

When running in dark mode (System Prefs > General > Use dark menu bar and Dock), this creates a white dot:

```
$ echo -n "black" | nc -4u -w0 localhost 1738
```

This is minor, arguably correct, but potentially misleading? Not sure if there's a better way here.

**Comment by tonsky** [comment]
I believe I've addressed it there https://github.com/tonsky/AnyBar/commit/3fc1eb35fdadb3439713adcb7214ce645ae0549d

Should work in v 0.1.2+
Works in my 10.12 Beta just fine

**Comment by tonsky** [comment]
Sorry, looks like I was running custom build of AnyBar. The issue was sort of addressed, but 0.1.3 release has black/white images messed up. I’ll fix than in next release, meanwhile, you can go to `AnyBar.app/Contents/Resources` and swap `black_alt@2x.png` and `white_alt@2x.png`
