### ISSUE TITLE
Custom Image AppleScript

### ISSUE THREAD

**Issue by moshed** [tonsky/AnyBar#60]
how would you set a custom image using applescript?
i would be comfortable doing it from terminal also but try to just change the color from terminal with `echo -n "black"  nc -4u -w0 localhost 1738` changes it for instant (ala issue #45) 

EDIT: i figured out why it was reverting back for me when using bash.  i was running a looping applescript to show the playing state of spotify and it was still running. oops

**Comment by moshed** [comment]
figured it out place images in  /path/to/AnyBar.app/Contents/Resources/ and use 
`tell application "AnyBar" to set image name to "image_name"`

**Comment by tonsky** [comment]
~/.AnyBar/ would work as well

**Comment by moshed** [comment]
i know this isnt the place for this but thanks so much for this! ive looked for years for a way to get a simple  play/pause indicator in my menubar like iOS of old had. i tried googling place custom images in menubar with a million variations to see if i could do it manually and finaly i stumbled in this awesome project!
