### ISSUE TITLE
How to prevent anybar from stealing my current window focus?

### ISSUE THREAD

**Issue by kols** [tonsky/AnyBar#70]
I run a launchd service which runs a bash script to update anybar status every 1m, and this will make anybar steal the window focus, which is very annoying.
How can I prevent this?

**Comment by tonsky** [comment]
I’m pretty sure AnyBar can’t steal your focus. Maybe your bash script does? How exactly are you communicating with anybar?

**Comment by kols** [comment]
I'm doing an `open -a AnyBar` without the `-g` flag to run anybar before changing its color.
My mistake, closing.
