### ISSUE TITLE
The executable in AnyBar-0.2.0.zip has version number 0.1.4

### ISSUE THREAD

**Issue by pro-sumer** [tonsky/AnyBar#77]
The executable in AnyBar-0.2.0.zip has version number 0.1.4

Is it the correct executable with a wrong version number? Or the wrong executable?

**Comment by core-code** [comment]
i can confirm the bug

<img width="261" alt="Screenshot 2020-08-26 at 21 31 13" src="https://user-images.githubusercontent.com/1261954/91348202-be07dc00-e7e3-11ea-9709-cb48bc7a06a8.png">
<img width="567" alt="Screenshot 2020-08-26 at 21 31 32" src="https://user-images.githubusercontent.com/1261954/91348230-c6601700-e7e3-11ea-80bc-abcb4844bc95.png">
<img width="597" alt="Screenshot 2020-08-26 at 21 31 49" src="https://user-images.githubusercontent.com/1261954/91348239-c8c27100-e7e3-11ea-9c5b-6f0e5c7e73cc.png">

**Comment by core-code** [comment]
the 'CFBundleShortVersionString' entry in the 'Info.plist' file is broken
