### ISSUE TITLE
Pass starting color to AnyBar?

### ISSUE THREAD

**Issue by Dima-369** [tonsky/AnyBar#80]
I really like AnyBar, good job 👍

One thing I would love to see though would be a way to set the initial color of the dot. Maybe there is even already something like this implemented?

Asking because calling `open -na Anybar && echo -n "green" | nc -4u -w0 localhost 1738` does not set the color of the dot to green, I think because `open` in itself operates in the background. 

One could insert a `sleep 0.5s` like this: `open -na Anybar && sleep 0.5s && echo -n "green" | nc -4u -w0 localhost 1738` but it flickers the dot color because it is set to white initially.

I think something like `ANYBAR_INITIAL_COLOR` would be amazing!

**Comment by tonsky** [comment]
Would you like to provide a PR?

**Comment by Dima-369** [comment]
I'll try.

**Comment by tonsky** [comment]
Fixed with #81

**Comment by tonsky** [comment]
Pushed 0.2.2 release
