### ISSUE TITLE
Error on trying to open the app

### ISSUE THREAD

**Issue by ShivanshRakesh** [tonsky/AnyBar#82]
On trying to open AnyBar, the following error pops up: [OS version: **macOS 10.15.7**]

<img width="500" alt="image" src="https://user-images.githubusercontent.com/49039969/98244427-70eb7780-1f95-11eb-9eb7-2434c17fb4db.png">

This however can be force-opened, but it would be better if it could be fixed.

**Comment by tonsky** [comment]
Is there something I can do, without buying a $100/year developer account?

**Comment by ShivanshRakesh** [comment]
Ohh, so it requires a paid account? I see. Then it's fine I guess 😅

Anyway, it works as expected. I thought I'd have to do the "Open Anyway" thing everytime I opened it, but that's not the case. So it's fine.
