### ISSUE TITLE
Big Sur dynamically switches between black and white icons depending on desktop background

### ISSUE THREAD

**Issue by 6twenty** [tonsky/AnyBar#84]
This means that choosing the image style based on whether dark mode is enabled or not is not sufficient to choose the correct image, as the menu bar may be using black icons or white icons regardless. This is a screenshot of my mac with dark mode enabled, but a light desktop background image, and setting anybar to the "black" image:

<img width="178" alt="image" src="https://user-images.githubusercontent.com/169607/107860490-7ca7dd80-6ea4-11eb-8fe9-bd450f154f2c.png">

My desktop image is a dynamic wallpaper, so in the evening it's much darker and the mac switches to using white icons.

**Comment by 6twenty** [comment]
Not that I know anything about Mac app development, but on reading up about this it sounds like the most reliable solution is to set `setTemplate:YES` on the "black" and "white" images so that the os can invert them automatically when it wants to use white menu bar icons instead of black ones. I imagine this would mean also removing the `_dark` code that switches to the "_alt" variants.

**Comment by tonsky** [comment]
Well the trick with _dark is that on "black" on light scheme is a filled circle but empty donut on a dark theme. It changes shape, otherwise filled black circle will become filled white circle, and calling filled white circle "black" is weird.

Is there any way to detect when Big Sur changes menubar color?

**Comment by 6twenty** [comment]
Ah, that's a good point. From the searches I did, no, there's no known Big Sur API to detect when it switches between white & black icons.

Would it be an option to add entirely separate images instead? E.g. "donut" and "fill" - using names that don't relate to light or dark at all - that have `setTemplate:YES` on just those ones?

**Comment by tonsky** [comment]
I am thinking making them black with white outline (`black`) and white with black outline (`white`). That way they will work on both backgrounds, without switching.

**Comment by tonsky** [comment]
Made `filled` and `hollow`, added inverted borders to `black` and `white`, removed `_alt` versions. Published 0.2.3. Thanks!

**Comment by 6twenty** [comment]
💐 thank you!
