### ISSUE TITLE
Alfred workflow link broken

### ISSUE THREAD

**Issue by tjluoma** [tonsky/AnyBar#85]
The main README page includes a link which displays as <https://github.com/raguay/MyAlfred> but actually links to <https://github.com/raguay/MyAlfred/blob/master/AnyBarWorkflow.alfredworkflow>.

That link is 404. 

However, there is a new link:

<https://github.com/raguay/MyAlfred/blob/master/Alfred%204/AnyBar%20Workflow.alfredworkflow>

which I believe is the same thing but apparently `raguay` reorganized their repo.

If you link to

<https://github.com/raguay/MyAlfred/raw/master/Alfred%204/AnyBar%20Workflow.alfredworkflow>

it should offer to download it directly.

**Comment by tonsky** [comment]
Thank you!
