### ISSUE TITLE
Would it be possible to not display a warning AnyBar icon in the menu bar when the port is already taken?

### ISSUE THREAD

**Issue by Dima-369** [tonsky/AnyBar#91]
I have a scenario where it can happen that some code launches AnyBar on the same port in quick succession which leads to warning icons displayed in the menu bar:

```shell
ANYBAR_PORT=1740 ANYBAR_INIT=green open -n /Applications/AnyBar.app
```

![image](https://user-images.githubusercontent.com/15002298/170943939-07425679-e624-4ff2-85d5-abbcbe5cc8c0.png)

Is it possible to change this, maybe via a new environment variable, to just exit AnyBar silently without displaying the warning?

**Comment by tonsky** [comment]
It feels like it’s better to check port before launching AnyBar in your case. Is that possible?

**Comment by Dima-369** [comment]
I am actually using the command below to only launch when the port is available, but because AnyBar takes a bit of time to startup, I still get some warning icons here and there.

```bash
lsof -Pn -i4 | grep 'AnyBar.*\\*:1740$' || ANYBAR_PORT=1740 ANYBAR_INIT=green open -n /Applications/AnyBar.app&
```

The code causing this is not fully under my control. Maybe I could implement some queue to the AnyBar interface though or just change the code below and attempt to build an `.app` myself:

```swift
NSLog(@"Error: %@: %@", ex.name, ex.reason);
_statusItem.image = [NSImage imageNamed:@"exclamation@2x.png"];
[_statusItem.image setTemplate:NO];
```

**Comment by tonsky** [comment]
I’m only resistant because it feels like very specific problem and I’m not sure if anyone will ever benefit from it. Building it from sources should be trivial btw — just install Xcode and click build. There’s no special build process or anything

**Comment by Dima-369** [comment]
Yeah, I forked and built without any problems and I agree, it is indeed a rather specific problem, so closing this as my trivial fix works.

**Comment by Dima-369** [comment]
If anyone else has the same issue, see https://github.com/Dima-369/AnyBar/commit/8ee11c6cd6b797d516fd58367a7f83baa41d82e9 for the fix.
