### ISSUE TITLE
"_alt" images for dark system appearance setting not working

### ISSUE THREAD

**Issue by joeynotjoe** [tonsky/AnyBar#93]
I'm running MacOS Ventura 13.1 and AnyBar version 0.2.3, and I can't seem to get any of the images with _alt added to the filename to work properly. Toggling system appearance seems to have no effect on the icons for me.

Using AnyBar version 0.2.2, toggling system preferences has the intended effect, and I'm able to have icon_alt@2x.png show up properly. It's just the 0.2.3 that doesn't seem to work.

Thanks! :)

**Comment by tonsky** [comment]
IIRC, this was removed because in Ventura icon colors do not depend on system theme anymore, but on wallpaper instead. See #84 for context

**Comment by joeynotjoe** [comment]
That makes so much sense, thank you. Sorry I missed that issue!
